// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ============ SINGLETON VERIFICATION ============
// CRITICAL: Ensure only ONE Supabase client instance exists
// Multiple instances cause auth state desync and session loops
declare global {
  interface Window {
    __sbClientCount?: number;
    __sbClientCreatedAt?: number;
  }
}

if (typeof window !== 'undefined') {
  window.__sbClientCount = (window.__sbClientCount ?? 0) + 1;
  window.__sbClientCreatedAt = Date.now();
  
  if (import.meta.env.DEV) {
    console.log(`[Supabase] Client instance #${window.__sbClientCount} created`);
    
    // Warn if more than 1 instance
    if (window.__sbClientCount > 1) {
      console.error('[Supabase] ⚠️ MULTIPLE CLIENT INSTANCES DETECTED! This causes auth issues.');
    }
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ── Flexible session storage ──────────────────────────────────────────────────
// Reads the user's "Manter conectado" preference (m3_keep_logged_in) on every
// read/write so the decision is always current — even during auto-refresh.
//   keep = true  → localStorage  (survives browser restarts, ~30-day effective TTL)
//   keep = false → sessionStorage (cleared when the tab/window is closed)
const flexStorage = {
  getItem(key: string): string | null {
    try {
      // sessionStorage wins: handles tabs opened without the keep flag
      return sessionStorage.getItem(key) ?? localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem(key: string, value: string): void {
    try {
      const keep = localStorage.getItem("m3_keep_logged_in") !== "false";
      if (keep) {
        localStorage.setItem(key, value);
        sessionStorage.removeItem(key);   // clear any leftover from a previous temp session
      } else {
        sessionStorage.setItem(key, value);
        localStorage.removeItem(key);     // ensure nothing persists across browser restarts
      }
    } catch { /* storage may be blocked in private mode */ }
  },
  removeItem(key: string): void {
    try {
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    } catch { /* ignore */ }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: flexStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});